{
  "bboxMode": 0,
  "collisionKind": 1,
  "type": 0,
  "origin": 0,
  "preMultiplyAlpha": false,
  "edgeFiltering": false,
  "collisionTolerance": 0,
  "swfPrecision": 2.525,
  "bbox_left": 0,
  "bbox_right": 433,
  "bbox_top": 0,
  "bbox_bottom": 93,
  "HTile": false,
  "VTile": false,
  "For3D": false,
  "width": 434,
  "height": 94,
  "textureGroupId": {
    "name": "Default",
    "path": "texturegroups/Default",
  },
  "swatchColours": null,
  "gridX": 0,
  "gridY": 0,
  "frames": [
    {"compositeImage":{"FrameId":{"name":"1b5ec021-fecc-48f7-92c6-9e9ca9c0414e","path":"sprites/spr_sound_toggle_on/spr_sound_toggle_on.yy",},"LayerId":null,"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},"images":[
        {"FrameId":{"name":"1b5ec021-fecc-48f7-92c6-9e9ca9c0414e","path":"sprites/spr_sound_toggle_on/spr_sound_toggle_on.yy",},"LayerId":{"name":"dd0b8246-c844-4d86-86f5-7271753994df","path":"sprites/spr_sound_toggle_on/spr_sound_toggle_on.yy",},"resourceVersion":"1.0","name":"","tags":[],"resourceType":"GMSpriteBitmap",},
      ],"parent":{"name":"spr_sound_toggle_on","path":"sprites/spr_sound_toggle_on/spr_sound_toggle_on.yy",},"resourceVersion":"1.0","name":"1b5ec021-fecc-48f7-92c6-9e9ca9c0414e","tags":[],"resourceType":"GMSpriteFrame",},
  ],
  "sequence": {
    "spriteId": {"name":"spr_sound_toggle_on","path":"sprites/spr_sound_toggle_on/spr_sound_toggle_on.yy",},
    "timeUnits": 1,
    "playback": 1,
    "playbackSpeed": 30.0,
    "playbackSpeedType": 0,
    "autoRecord": true,
    "volume": 1.0,
    "length": 1.0,
    "events": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MessageEventKeyframe>",},
    "moments": {"Keyframes":[],"resourceVersion":"1.0","resourceType":"KeyframeStore<MomentsEventKeyframe>",},
    "tracks": [
      {"name":"frames","spriteId":null,"keyframes":{"Keyframes":[
            {"id":"4e6c39c7-cca4-4804-a7e1-6b04c24373dd","Key":0.0,"Length":1.0,"Stretch":false,"Disabled":false,"IsCreationKey":false,"Channels":{"0":{"Id":{"name":"1b5ec021-fecc-48f7-92c6-9e9ca9c0414e","path":"sprites/spr_sound_toggle_on/spr_sound_toggle_on.yy",},"resourceVersion":"1.0","resourceType":"SpriteFrameKeyframe",},},"resourceVersion":"1.0","resourceType":"Keyframe<SpriteFrameKeyframe>",},
          ],"resourceVersion":"1.0","resourceType":"KeyframeStore<SpriteFrameKeyframe>",},"trackColour":0,"inheritsTrackColour":true,"builtinName":0,"traits":0,"interpolation":1,"tracks":[],"events":[],"modifiers":[],"isCreationTrack":false,"resourceVersion":"1.0","tags":[],"resourceType":"GMSpriteFramesTrack",},
    ],
    "visibleRange": null,
    "lockOrigin": false,
    "showBackdrop": true,
    "showBackdropImage": false,
    "backdropImagePath": "",
    "backdropImageOpacity": 0.5,
    "backdropWidth": 1366,
    "backdropHeight": 768,
    "backdropXOffset": 0.0,
    "backdropYOffset": 0.0,
    "xorigin": 0,
    "yorigin": 0,
    "eventToFunction": {},
    "eventStubScript": null,
    "parent": {"name":"spr_sound_toggle_on","path":"sprites/spr_sound_toggle_on/spr_sound_toggle_on.yy",},
    "resourceVersion": "1.3",
    "name": "spr_sound_toggle_on",
    "tags": [],
    "resourceType": "GMSequence",
  },
  "layers": [
    {"visible":true,"isLocked":false,"blendMode":0,"opacity":100.0,"displayName":"default","resourceVersion":"1.0","name":"dd0b8246-c844-4d86-86f5-7271753994df","tags":[],"resourceType":"GMImageLayer",},
  ],
  "parent": {
    "name": "options",
    "path": "folders/Sprites/options.yy",
  },
  "resourceVersion": "1.0",
  "name": "spr_sound_toggle_on",
  "tags": [],
  "resourceType": "GMSprite",
}